data:
  batch_size: 1
  num_workers: 0
  image_size: 200

path:
  train_path: asl_alphabet_train\\asl_alphabet_train
  test_path : asl_alphabet_test\\asl_alphabet_test

train:
  epoch: 30
  optimizer: Adam
  epoch: 50
  lr: 0.00001